### ISSUE TITLE
Change Type

### ISSUE THREAD

**Issue by llessurt** [VisualBean/VSTSTools#10]
git log -m -1 --name-status --pretty=format: e3b718d584b381f842dc8fb8f63cfeadcd8cbf2c

Exception calling "Substring" with "2" argument(s): "Index and length must refer to a location within the string.

**Comment by VisualBean** [comment]
What sort of input values are you using?

**Comment by VisualBean** [comment]
Try running the git log command locally and send me the output.
It seems a recent change (getting renames to work) has caused the issue.

**Comment by VisualBean** [comment]
Thank you for submitting this issue.
Could you try running `git log -m -1 --name-status --pretty=format: e3b718d584b381f842dc8fb8f63cfeadcd8cbf2c` locally and provide me with the input?

It seems a recent change (getting renames to work) has caused the issue.

**Comment by VisualBean** [comment]
The issue it with multiple parents in a given commit - git log appends a blank line.

It has been fixed. - please try your build again :)

Thanks again for reporting the error.
