### ISSUE TITLE
Prerequisites should be listed in the read me file 

### ISSUE THREAD

**Issue by jl-rey** [VisualBean/VSTSTools#2]
You list the following Prerequisites:
### Prerequisites * Repository must be VSTS Git. * Allow scripts to access Oauth must be **Enabled** * Project Collection Build Service must have **Contribute** & **Create Tag** set to **Allow** or **Inherit Allow** for that particular repository

These should be listed in the read me and on the web page.
Also Instructions for how to set these would be good.

I found the Oauth and enabled that.

## Am unable to find how to change the Project Collection Build Service:
On the Build Security these options are not listed.

Jlr

**Comment by jl-rey** [comment]
Found where to set the contribute permission.

This seem to work.

**Comment by arroyoshipp** [comment]
Prequisites *Repository must be VSTS Git. *Allow scripts to access Oauth must be Enabled. *Project Collection Built Service must have Contribute & Create Tag set to Allow or Inherit Allow for that particular Repository.
Am unable to find how to change the Project Collection Built Service:
