### ISSUE TITLE
Error: A supported task execution handler was not found.

### ISSUE THREAD

**Issue by kwtangerine** [VisualBean/VSTSTools#8]
Got this error when running the task:
```
[error]A supported task execution handler was not found. This error usually means the task does not carry an implementation that is compatible with your current operating system. Contact the task author for more details.
```

Seems like I might miss some prerequisites but not sure what. I've ensured all these already:
```
- Repository must be VSTS Git.
- Allow scripts to access Oauth must be Enabled
- Project Collection Build Service must have Contribute & Create Tag set to Allow or Inherit Allow for that particular repository
```

**Comment by kwtangerine** [comment]
Does the extension only support windows agents?

**Comment by VisualBean** [comment]
I guess it does :) - I will put that prerequisite in the list aswell. I am really sorry about the trouble. ( ill look into a cross platform solution, but at the moment, the task is written in powershell. )

Again, sorry for the inconvenience

**Comment by kwtangerine** [comment]
No worries, for the moment I've setup a group task that runs a sequence of git cmd line tasks.. it's not ideal but it works for my setup. :)

**Comment by VisualBean** [comment]
@kwtangerine Great! - Have you seen Powershell Core? - it might actually fix the issue for the linux agent.
It does feel like a hack though, installing Powershell on a linux host :).

Anyway - thanks for the report. Ill close the task and look into creating a cross platform solution
