### ISSUE TITLE
Adding "Working directory" field

### ISSUE THREAD

**Issue by GrimSmiler** [VisualBean/VSTSTools#9]
Hi!

Is it possible to add a Working directory field?
The commands in the step should be executed in that directory.

This would solve an issue that i have:
Using the step in the release definition fails to find the repo root.
The reason for this failure is because the repo root is one folder deeper.

Thank You in Advance!

Best Regards,
GrimSmiler

**Comment by VisualBean** [comment]
Hi,
I've updated the Task. 67dc6022f22f857fdd93fba344141d859d57b473

The task have moved to a different publisher, I think you need to redownload.


Please find it here -> https://marketplace.visualstudio.com/items?itemName=ATP.ATP-GitTag

**Comment by GrimSmiler** [comment]
Thanks! this fixed all the problems i had!
